export const TEACHER_LOGGEDIN = 'TEACHER_LOGGEDIN'
export const TEACHER_LOGIN = 'TEACHER_LOGIN'
export const TEACHER_LOGIN_FAILED = 'TEACHER_LOGIN_FAILED'

export const CACHE_HOUSES = 'CACHE_HOUSES'
export const CACHE_TEACHERS = 'CACHE_TEACHERS'
export const CACHE_REASONS = 'CACHE_REASONS'

export const RENAVIGATE = 'RENAVIGATE'
export const BACK = 'BACK'
export const POPTOTOP = 'POPTOTOP'