export const TEACHER_RESOLVE_KEYCODE = 'TEACHER_RESOLVE_KEYCODE'
export const TEACHER_RESOLVE_KEYCODE_FAILED = 'TEACHER_RESOLVE_KEYCODE_FAILED'
export const TEACHER_RESOLVE_KEYCODE_SUCCESS = 'TEACHER_RESOLVE_KEYCODE_SUCCESS'

export const TEACHER_SAVE = 'TEACHER_SAVE'
export const TEACHER_SAVE_FAILED = 'TEACHER_SAVE_FAILED'
export const TEACHER_SAVE_SUCCESS = 'TEACHER_SAVE_SUCCESS'
export const TEACHER_CLEAR = 'TEACHER_CLEAR'
